# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# This R script can be used to find the statename given a code corresponding  #
# alphabetically to the correct state. After this, the codes are based on     #
# the National Weather Service Regions to use with weather/NCDC data          #
#                                                                             #
# Author: April Walker                                                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

findState <- function(code) {
  states <- c(
            "001"="Alabama",
            "002"="Arizona",
            "003"="Arkansas",
            "004"="California",
            "005"="Colorado",
            "006"="Connecticut",
            "007"="Delaware",
            "008"="Florida",
            "009"="Georgia",
            "010"="Idaho",
            "011"="Illinois",
            "012"="Indiana",
            "013"="Iowa",
            "014"="Kansas",
            "015"="Kentucky",
            "016"="Louisiana",
            "017"="Maine",
            "018"="Maryland",
            "019"="Massachusetts",
            "020"="Michigan",
            "021"="Minnesota",
            "022"="Mississippi",
            "023"="Missouri",
            "024"="Montana",
            "025"="Nebraska",
            "026"="Nevada",
            "027"="New Hampshire",
            "028"="New Jersey",
            "029"="New Mexico",
            "030"="New York",
            "031"="North Carolina",
            "032"="North Dakota",
            "033"="Ohio",
            "034"="Oklahoma",
            "035"="Oregon",
            "036"="Pennsylvania",
            "037"="Rhode Island",
            "038"="South Carolina",
            "039"="South Dakota",
            "040"="Tennessee",
            "041"="Texas",
            "042"="Utah",
            "043"="Vermont",
            "044"="Virginia",
            "045"="Washington",
            "046"="West Virginia",
            "047"="Wisconsin",
            "048"="Wyoming",
            "049"="Hawaii",
            "050"="Alaska",
            "101"="Northeast Region",
            "102"="East North Central Region",
            "103"="Central Region",
            "104"="Southeast Region",
            "105"="West North Central Region",
            "106"="South Region",
            "107"="Southwest Region",
            "108"="Northwest Region",
            "109"="West Region",
            "110"="National",
            "111"="Great Plains",
            "115"="Southern Plains and Gulf Coast",
            "120"="US Rockies and Westward",
            "121"="NWS Eastern Region",
            "122"="NWS Southern Region",
            "123"="NWS Central Region",
            "124"="NWS Western Region",
            "201"="Pacific Northwest Basin",
            "202"="California River Basin",
            "203"="Great Basin",
            "204"="Lower CO River Basin",
            "205"="Upper CO River Basin",
            "206"="Rio Grande River Basin",
            "207"="TX Gulf Coast River Basin",
            "208"="AR-White-Red Basin",
            "209"="Lower MS River Basin",
            "210"="MS River Basin",
            "211"="Souris-Red-Rainy Basin",
            "212"="Upper MS River Basin",
            "213"="Great Lakes Basin",
            "214"="TN River Basin",
            "215"="OH River Basin",
            "216"="South Atlantic-Gulf Basin",
            "217"="Mid-Atlantic Basin",
            "218"="New England Basin",
            "220"="MS River Basin & Tributaties",
            "250"="Spring Wheat Belt",
            "255"="Primary Hard Red Winter Wheat Belt",
            "256"="Winter Wheat Belt",
            "260"="Primary Corn and Soybean Belt",
            "261"="Corn Belt",
            "262"="Soybean Belt",
            "265"="Cotton Belt",
            "350"="Spring Wheat Belt",
            "356"="Winter Wheat Belt",
            "361"="Corn Belt",
            "362"="Soybean Belt",
            "365"="Cotton Belt",
            "450"="Spring Wheat Belt",
            "456"="Winter Wheat Belt",
            "461"="Corn Belt",
            "462"="Soybean Belt",
            "465"="Cotton Belt"
            )
  statename <- as.character(states[code])
  return(statename)
}
